---
- name: add nginx public key
  apt_key:
    id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    keyserver: keyserver.ubuntu.com

- name: add nginx repository
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx"

- name: install packages
  apt:
    name: nginx

- name: delete default nginx configuration
  file:
    dest: /etc/nginx/conf.d/default.conf
    state: absent

- name: configure logrotate
  copy:
    src: logrotate.conf
    dest: /etc/logrotate.d/nginx

- name: copy dhparam.pem
  copy:
    src: dhparam.pem
    dest: /etc/nginx/dhparam.pem
  notify: reload nginx

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: create /srv/www/default
  file:
    dest: /srv/www/default
    state: directory
