---
- name: update APT cache
  apt: update_cache=yes

- name: reconfigure tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- name: reload ferm
  service: name=ferm state=reloaded
